import { Make } from './make';

export const MAKING: Make [] = [
    { name: 'The coffee bean process', description: ['Before you brew your Masterton’s Coffee, take a moment to look carefully at the beans. Smell their aroma. Think of the many processes that these beans have gone through since the day they were hand-picked and sorted in their origin country. Consider the long way they have travelled to your kitchen. Prepare your coffee thoughtfully and enjoy it with pleasure. Many people have been instrumental in bringing it to your cup!',
            'The two coffee beans make up only one third of the coffee berry, the rest consisting of fruit flesh (also known as pulp), skin and husk, all of which must be removed so that only the green beans remain.',
            'Two different methods of processing the coffee beans have now been adopted worldwide: wet processing and dry processing:',
            'Wet processing, whereby the beans are washed, is mainly employed in Central America and parts of Africa (notably Kenya). This process is relatively expensive, but is beneficial to the quality of the coffee. The berries are first fed through a water channel to soak them and to remove any impurities. The unripe berries sink to the bottom, leaving the ripe fruit to float to the top.',
            'The ripe berries can then be processed further. The fruit flesh of the berries is removed with the help of a ‘de-pulper’, a machine that has a roller with a roughened surface. This scours away the fruit flesh (pulp) from the berries under a stream of water. Previously, the remaining pulp was treated as waste, but nowadays it is blended with minerals and turned into fertiliser.',
            'In the second stage of wet processing the coffee beans are fermented in large water containers. The object of the fermentation process is not only to dissolve any remaining fruit flesh, but also to remove the sticky film surrounding the coffee beans, which is not water soluble. This part of the procedure, which lasts approximately two days, is very important. The long period of fermentation is what first gives the coffee its rich aroma and special flavour.',
            'WASHING: On completion of the fermentation process the coffee beans have to be washed. At this stage, the beans are still surrounded by their parchment husk, and for this reason the coffee is also referred to as ‘parchment coffee’.',
            'DRYING: The washed parchment coffee is then spread out on concrete slabs or drying racks and left out in the sun. To ensure that the beans dry evenly they are turned over several times a day. Depending on the weather conditions, this process takes five or six days. Cultivators operating on a medium to large scale make use of drying machines, huge metal drums inside which hot air circulates. Again, to ensure that the beans dry evenly the drums rotate continually.',
            'HULLING: Next the pergamino is stored in bags, before being mechanically hulled by special machines. These peeling machines have grooved cast iron cylinders, inside which the husk of the coffee beans is scoured away as they rub against one another. At the end of this process the beans are generally olive green in colour. Some varieties even have blue beans; these are the high quality so-called ‘blue’ coffees.',
            'SORTING: First the coffee beans are sieved to remove any foreign objects and damaged beans. Next they are mechanically graded according to size and shape. This is followed by a further selection process, this time carried out by trained workers. The coffee is sorted by eye as it passes in front of them on a conveyor belt into the different quality grades. There are also machines now that can perform this selection work.',
            'In Brazil and across a large part of Africa, dry processing is used for lower quality Arabica and Robusta berries, a simple technique which is less labour intensive than wet processing. However, cheaper production costs must be offset against a loss in quality, since the length of the process (the drying of the berries) is dependent on the unpredictable climate. Once all twigs, leaves, stones and other foreign objects have been sieved out, dry processing can begin. The berries are spread out in the sun on cement or brick slabs in layers five to six cm deep. To ensure that the beans dry evenly, the berries are turned regularly for a period of two to three weeks. On smaller plantations drying mats made of wire netting are often used.',
            'HULLING: Once the beans are completely dry, hulling begins. In a peeling machine similar to that used during wet processing, the dried fruit flesh (the pulp), the parchment skin and a part of the husk that surrounds the coffee bean are removed.',
            'SORTING: Finally, the beans are cleaned and then sorted according to size by mechanically operating vibrating sieves. The beans are then measured into sacks of a standard size (usually 60 kg)'
]},
    { name: 'The machinery used', description: ['Wet coffee processing systems: this process consists of a Cleated conveyor, Feeds coffee cherries from the loading pit to the washer, a Cherry Washer, Cleans coffee cherries, and separates sink cherries (ripe cherries, green cherries) from floating cherries (withered, pestilent insects), a Pulp remover, Removes pulps from parchment coffee, a Cherry Pulper and Seperator, Removes the pulps outside of coffee cherries, a Mucilage Remover, Removes the mucilage sticks on parchment coffee, and does not affect the coffee beans, a Water Drainer,Removes water from parchment coffee after mucilage removal, a Storage Silo, Stores clean parchment coffee or other agricultural products for drying, a Bucket elevator,Conveys materials to next stage in the processing system vertically and finally a Cherry pulper (small quantities), Removes pulps outside of coffee cherries',
            'Dried cherry and parchment coffee processing system: invovles a pre-celeaner, Eleminates impurities for some agricultural granular products such as coffee beans, pepper, corn, green beans, etc., a Rotary Magnetic Seperator, Eleminates iron and steel mixed in grains, such as: green coffee beans, pepper, corn, etc. and finally a Huller and Polisher, Removes dried husks and parchment from green coffee beans.',
            'Green coffee processing system: involves a Pre-cleaner, Eleminates impurities for some agricultural granular products such as coffee beans, pepper, corn, green beans, etc., a De-stoner, Eleminates stones in the granular materials such as green coffee beans, grean beans, soya beans, etc., a Rotary Magnetic seperator, Eleminates iron and steel mixed in grains, such as: green coffee beans, pepper, corn, etc., a Size Grader, Separates green coffee beans into different sizes, a Gravity Seperator, Separates coffee beans and other agricultural granular products by their specific weight, a Washing and Refining machine, Removes silver skins, polish the coffee beans, a Storage Silo, Stores green coffee beans for bagging, and finally a Bucket Elevator, Conveys materials to next stage in the processing system vertically.',
            'The drying system: this system may consist of a DRUM DRYER, a TOWER DRYER, a STATIC DRYER and a FLUID BED DRYER.',
            'The Roasting and Grinding systems: involves a Roaster series 2.5kg, 5kg, 12kg,or a 30kg, this posesses MULTIPLE fuctions for various roasting styles, a Coffee Grinder MXR-series - 500kg, 1000kg, 1500kg, 2000kg, Used to grind coffee beans to coffee powder with homogeneous particle sizes, and unchaged quality. High economic saving and aesthetic. It also has a Roaster MR-series - 60kg, 120kg, 250kg, batch Fully automatic control of roasting process via PLC. Capacities: 60 kg - 120 kg - 250 kg/batch, a Multi-compartment Silo, Tank body is fabricated from steel and electrostatic paint, Coffee Scaling equipment, This scale is auto-controlled for use in roasting and grinding coffee, a Fermentation tank for roasted coffee beans, Used for fermentation of roasted coffee, a Coffee Mixer, This coffee mixer is usually used for mixing coffee after roasting or grinding, and a Coffee Powder Storage Silo, Used to contain coffee powder after grinding. Features a full and empty sensor.'
]},
    { name: 'Behind the scenes', description: ['The coffees we have come to love and enjoy are nothing without the people who are skilled enough to make the coffee itself, from seed to bean to coffee.',
            'Like any business there are plenty of safety regulations to follow in order to export the contents worldwide:',
            'The ICO promotes good food safety practices throughout the coffee chain, addressing both the concerns of producing countries in building capacity, and consumer health concerns of regulatory bodies.',
            'Phytosanitary issues are regularly reviewed by the Private Sector Consultative Board and the Council which receive reports on food safety issues and legislative developments, ranging from maximum residue levels of pesticides permitted by importing countries to acrylamide and OTA.',
            'Improving quality is crucial to sustaining consumption in the long term and adding value to coffee. The Coffee Quality-Improvement Programme (CQP) contributes to improved food safety, establishing certain basic quality standards to prevent the presence of contaminants in shipments and make it more attractive to both retailers and consumers.',
            'Under the CQP moisture content should not fall below 8% or exceed 12.5% and there should be no more than 86 or 150 defects per 300g sample of Arabica and Robusta coffee respectively. The ICO also discourages trading coffee with less than equivalent of 95% green coffee as the basic raw material.',
            'Managing pests and diseases: Action against pests and diseases is important to protect the economies of producing countries and the livelihoods of farming populations and to protect quality. ICO/CFC sponsored projects promote sustainable development by introducing effective integrated pest management systems and reducing the use of chemical pest control methods. The coffee berry borer, coffee wilt disease, white stem borer and leaf rust are examples of pests and diseases tackled through projects. The ICO also sponsors projects to enhance processing practices to add value and decrease contamination. A US$6 million project to reduce mould formation in coffee resulted in a website ‘Reducing OTA in Coffee’ (www.coffee-ota.org) and a CD-Rom training tool ‘Good hygiene Practices along the coffee chain’ published in English, French and Spanish.',
            'Cooperation with international bodies: The ICO is an accredited observer to Codex Alimentarius and has actively contributed to the development of a code of conduct for the prevention of OTA by this body. The ICO also cooperates with the Association for Science and Information on Coffee which holds international conferences at which scientists present the latest findings on scientific research and technological developments in the area of coffee.',
            'Workshops and seminars: The ICO regularly organizes seminars and workshops to inform Members of the latest developments in fields such as Genetically Modified Coffee and the Coffee Berry Borer. Expert speakers present the latest findings and the presentations are disseminated to the world coffee sector through the ICO website.'
]}
];
